# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32bea83ed6a4d3ec6a18d426e7fed3580f5242f1b5608627704d2d326d13f6791d0699a74a04792edaad40a1b29c2d120d53b5785890980cbc0aeab5b5a45baa

test:
  secret_key_base: c54815f35dcee79415a201a7d986c35e9836728736c12a7bda5e9f58ed4b4d69bfb4b67b43d66b6a0bce446a879fc935043fbc13475a04fb6271fff0b9005cd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
